default:
  - 'serve'

serve:
  - 'express'
  - 'watch'

build:
  - 'clean:build'
  - 'jade:compile'
  - 'compass'
  - 'autoprefixer'
  - 'cssmin'
  - 'jshint'
  - 'concat'
  - 'uglify'
  - 'copy'

copy_assets:
  - 'copy'

js_watcher_tasks:
  - 'jshint:scripts'
  - 'concat'
  - 'clean:js'
  - 'uglify'

css_watcher_tasks:
  - 'compass'
  - 'autoprefixer'
  - 'clean:css'
  - 'cssmin'
